import {
  describe, test,
} from 'vitest';
import { Validator } from './validator';

class TestMaterialize extends Validator {
  override dialect = 'materialize' as const;

  testMaterialize () {
    this.validateAll(
      'CREATE TABLE example (id INT PRIMARY KEY, name TEXT)',
      {
        write: {
          materialize: 'CREATE TABLE example (id INT, name TEXT)',
          postgres: 'CREATE TABLE example (id INT PRIMARY KEY, name TEXT)',
        },
      },
    );
    this.validateAll(
      'INSERT INTO example (id, name) VALUES (1, \'Alice\') ON CONFLICT(id) DO NOTHING',
      {
        write: {
          materialize: 'INSERT INTO example (id, name) VALUES (1, \'Alice\')',
          postgres: 'INSERT INTO example (id, name) VALUES (1, \'Alice\') ON CONFLICT(id) DO NOTHING',
        },
      },
    );
    this.validateAll(
      'CREATE TABLE example (id SERIAL, name TEXT)',
      {
        write: {
          materialize: 'CREATE TABLE example (id INT NOT NULL, name TEXT)',
          postgres: 'CREATE TABLE example (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name TEXT)',
        },
      },
    );
    this.validateAll(
      'CREATE TABLE example (id INT AUTO_INCREMENT, name TEXT)',
      {
        write: {
          materialize: 'CREATE TABLE example (id INT NOT NULL, name TEXT)',
          postgres: 'CREATE TABLE example (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name TEXT)',
        },
      },
    );
    this.validateAll(
      'SELECT JSON_EXTRACT_PATH_TEXT(\'{ "farm": {"barn": { "color": "red", "feed stocked": true }}}\', \'farm\', \'barn\', \'color\')',
      {
        write: {
          materialize: 'SELECT JSON_EXTRACT_PATH_TEXT(\'{ "farm": {"barn": { "color": "red", "feed stocked": true }}}\', \'farm\', \'barn\', \'color\')',
          postgres: 'SELECT JSON_EXTRACT_PATH_TEXT(\'{ "farm": {"barn": { "color": "red", "feed stocked": true }}}\', \'farm\', \'barn\', \'color\')',
        },
      },
    );
    this.validateAll(
      'SELECT MAP[\'a\' => 1]',
      {
        write: {
          duckdb: 'SELECT MAP {\'a\': 1}',
          materialize: 'SELECT MAP[\'a\' => 1]',
        },
      },
    );

    this.validateIdentity('CURRENT_TIMESTAMP');
    this.validateIdentity('NOW()', 'CURRENT_TIMESTAMP');
    this.validateIdentity('MZ_NOW()');

    this.validateIdentity('SELECT CAST(1 AS mz_timestamp)');

    this.validateIdentity('CREATE TABLE example (id INT, name LIST)');

    this.validateIdentity('SELECT LIST[]');
    this.validateIdentity('SELECT LIST[1, 2, 3]');
    this.validateIdentity('SELECT LIST[LIST[1], LIST[2], NULL]');
    this.validateIdentity('SELECT CAST(LIST[1, 2, 3] AS INT LIST)');
    this.validateIdentity('SELECT CAST(NULL AS INT LIST)');
    this.validateIdentity('SELECT CAST(NULL AS INT LIST LIST LIST)');
    this.validateIdentity('SELECT LIST(SELECT 1)');

    this.validateIdentity('SELECT MAP[]');
    this.validateIdentity('SELECT MAP[\'a\' => MAP[\'b\' => \'c\']]');
    this.validateIdentity('SELECT CAST(MAP[\'a\' => 1] AS MAP[TEXT => INT])');
    this.validateIdentity('SELECT CAST(NULL AS MAP[TEXT => INT])');
    this.validateIdentity('SELECT CAST(NULL AS MAP[TEXT => MAP[TEXT => INT]])');
    this.validateIdentity('SELECT MAP(SELECT \'a\', 1)');
  }
}

const t = new TestMaterialize();
describe('TestMaterialize', () => {
  test('materialize', () => t.testMaterialize());
});
