import { readFileSync } from 'node:fs';
import {
  join, dirname,
} from 'path';
import { fileURLToPath } from 'node:url';
import {
  expect,
} from 'vitest';

const filename = fileURLToPath(import.meta.url);
const fileDir = dirname(filename);
const fixturesDir = join(fileDir, 'fixtures');

function filterComments (sql: string): string {
  return sql
    .split('\n')
    .filter((line) => line.trim() && !line.startsWith('--'))
    .join('\n');
}

function extractMeta (sql: string): [string, Record<string, string>] {
  const meta: Record<string, string> = {};
  const sqlLines = sql.split('\n');
  let i = 0;

  while (i < sqlLines.length && sqlLines[i].startsWith('#')) {
    const parts = sqlLines[i].split(':');
    const key = parts[0].replace(/^#/, '').trim();
    const val = parts.slice(1).join(':')
      .trim();
    meta[key] = val;
    i++;
  }

  const remainingSql = sqlLines.slice(i).join('\n');
  return [remainingSql, meta];
}

/**
 * Asserts that a Vitest mock logger contains a specific message.
 */
export function assertLoggerContains (message: string, logger: Console, level: string = 'error'): void {
  const mockCalls = logger[level]?.mock?.calls || [];
  const output = mockCalls
    .map((args: unknown[]) => String(args[0]))
    .join('\n');

  expect(output).toContain(message);
}

export function* loadSqlFixtures (filename: string): Generator<string> {
  const filePath = join(fixturesDir, filename);
  const data = readFileSync(filePath, 'utf-8');
  const filtered = filterComments(data);

  for (const line of filtered.split('\n')) {
    yield line;
  }
}

export function* loadSqlFixturePairs (filename: string): Generator<[Record<string, string>, string, string]> {
  const filePath = join(fixturesDir, filename);
  const data = readFileSync(filePath, 'utf-8');
  const statements = filterComments(data).split(';');

  for (let i = 0; i < statements.length; i += 2) {
    if (i + 1 < statements.length) {
      const sqlRaw = statements[i].trim();
      const [parsedSql, meta] = extractMeta(sqlRaw);
      const expected = statements[i + 1].trim();
      yield [
        meta,
        parsedSql,
        expected,
      ];
    }
  }
}

export function stringToBool (val: string | boolean | undefined): boolean {
  if (val === undefined) return false;
  if (typeof val === 'boolean') return val;
  return ['true', '1'].includes(val.toLowerCase());
}

export const skipIntegration = stringToBool(process.env.SKIP_INTEGRATION || '0');

export const tpchSchema: Record<string, Record<string, string>> = {
  lineitem: {
    lOrderkey: 'bigint',
    lPartkey: 'bigint',
    lSuppkey: 'bigint',
    lLinenumber: 'bigint',
    lQuantity: 'double',
    lExtendedprice: 'double',
    lDiscount: 'double',
    lTax: 'double',
    lReturnflag: 'string',
    lLinestatus: 'string',
    lShipdate: 'string',
    lCommitdate: 'string',
    lReceiptdate: 'string',
    lShipinstruct: 'string',
    lShipmode: 'string',
    lComment: 'string',
  },
  orders: {
    oOrderkey: 'bigint',
    oCustkey: 'bigint',
    oOrderstatus: 'string',
    oTotalprice: 'double',
    oOrderdate: 'string',
    oOrderpriority: 'string',
    oClerk: 'string',
    oShippriority: 'int',
    oComment: 'string',
  },
  customer: {
    cCustkey: 'bigint',
    cName: 'string',
    cAddress: 'string',
    cNationkey: 'bigint',
    cPhone: 'string',
    cAcctbal: 'double',
    cMktsegment: 'string',
    cComment: 'string',
  },
  part: {
    pPartkey: 'bigint',
    pName: 'string',
    pMfgr: 'string',
    pBrand: 'string',
    pType: 'string',
    pSize: 'int',
    pContainer: 'string',
    pRetailprice: 'double',
    pComment: 'string',
  },
  supplier: {
    sSuppkey: 'bigint',
    sName: 'string',
    sAddress: 'string',
    sNationkey: 'bigint',
    sPhone: 'string',
    sAcctbal: 'double',
    sComment: 'string',
  },
  partsupp: {
    psPartkey: 'bigint',
    psSuppkey: 'bigint',
    psAvailqty: 'int',
    psSupplycost: 'double',
    psComment: 'string',
  },
  nation: {
    nNationkey: 'bigint',
    nName: 'string',
    nRegionkey: 'bigint',
    nComment: 'string',
  },
  region: {
    rRegionkey: 'bigint',
    rName: 'string',
    rComment: 'string',
  },
};

export const tpcdsSchema: Record<string, Record<string, string>> = {
  catalogSales: {
    csSoldDateSk: 'bigint',
    csSoldTimeSk: 'bigint',
    csShipDateSk: 'bigint',
    csBillCustomerSk: 'bigint',
    csBillCdemoSk: 'bigint',
    csBillHdemoSk: 'bigint',
    csBillAddrSk: 'bigint',
    csShipCustomerSk: 'bigint',
    csShipCdemoSk: 'bigint',
    csShipHdemoSk: 'bigint',
    csShipAddrSk: 'bigint',
    csCallCenterSk: 'bigint',
    csCatalogPageSk: 'bigint',
    csShipModeSk: 'bigint',
    csWarehouseSk: 'bigint',
    csItemSk: 'bigint',
    csPromoSk: 'bigint',
    csOrderNumber: 'bigint',
    csQuantity: 'bigint',
    csWholesaleCost: 'double',
    csListPrice: 'double',
    csSalesPrice: 'double',
    csExtDiscountAmt: 'double',
    csExtSalesPrice: 'double',
    csExtWholesaleCost: 'double',
    csExtListPrice: 'double',
    csExtTax: 'double',
    csCouponAmt: 'double',
    csExtShipCost: 'double',
    csNetPaid: 'double',
    csNetPaidIncTax: 'double',
    csNetPaidIncShip: 'double',
    csNetPaidIncShipTax: 'double',
    csNetProfit: 'double',
  },
  catalogReturns: {
    crReturnedDateSk: 'bigint',
    crReturnedTimeSk: 'bigint',
    crItemSk: 'bigint',
    crRefundedCustomerSk: 'bigint',
    crRefundedCdemoSk: 'bigint',
    crRefundedHdemoSk: 'bigint',
    crRefundedAddrSk: 'bigint',
    crReturningCustomerSk: 'bigint',
    crReturningCdemoSk: 'bigint',
    crReturningHdemoSk: 'bigint',
    crReturningAddrSk: 'bigint',
    crCallCenterSk: 'bigint',
    crCatalogPageSk: 'bigint',
    crShipModeSk: 'bigint',
    crWarehouseSk: 'bigint',
    crReasonSk: 'bigint',
    crOrderNumber: 'bigint',
    crReturnQuantity: 'bigint',
    crReturnAmount: 'double',
    crReturnTax: 'double',
    crReturnAmtIncTax: 'double',
    crFee: 'double',
    crReturnShipCost: 'double',
    crRefundedCash: 'double',
    crReversedCharge: 'double',
    crStoreCredit: 'double',
    crNetLoss: 'double',
  },
  inventory: {
    invDateSk: 'bigint',
    invItemSk: 'bigint',
    invWarehouseSk: 'bigint',
    invQuantityOnHand: 'bigint',
  },
  storeSales: {
    ssSoldDateSk: 'bigint',
    ssSoldTimeSk: 'bigint',
    ssItemSk: 'bigint',
    ssCustomerSk: 'bigint',
    ssCdemoSk: 'bigint',
    ssHdemoSk: 'bigint',
    ssAddrSk: 'bigint',
    ssStoreSk: 'bigint',
    ssPromoSk: 'bigint',
    ssTicketNumber: 'bigint',
    ssQuantity: 'bigint',
    ssWholesaleCost: 'double',
    ssListPrice: 'double',
    ssSalesPrice: 'double',
    ssExtDiscountAmt: 'double',
    ssExtSalesPrice: 'double',
    ssExtWholesaleCost: 'double',
    ssExtListPrice: 'double',
    ssExtTax: 'double',
    ssCouponAmt: 'double',
    ssNetPaid: 'double',
    ssNetPaidIncTax: 'double',
    ssNetProfit: 'double',
  },
  storeReturns: {
    srReturnedDateSk: 'bigint',
    srReturnTimeSk: 'bigint',
    srItemSk: 'bigint',
    srCustomerSk: 'bigint',
    srCdemoSk: 'bigint',
    srHdemoSk: 'bigint',
    srAddrSk: 'bigint',
    srStoreSk: 'bigint',
    srReasonSk: 'bigint',
    srTicketNumber: 'bigint',
    srReturnQuantity: 'bigint',
    srReturnAmt: 'double',
    srReturnTax: 'double',
    srReturnAmtIncTax: 'double',
    srFee: 'double',
    srReturnShipCost: 'double',
    srRefundedCash: 'double',
    srReversedCharge: 'double',
    srStoreCredit: 'double',
    srNetLoss: 'double',
  },
  webSales: {
    wsSoldDateSk: 'bigint',
    wsSoldTimeSk: 'bigint',
    wsShipDateSk: 'bigint',
    wsItemSk: 'bigint',
    wsBillCustomerSk: 'bigint',
    wsBillCdemoSk: 'bigint',
    wsBillHdemoSk: 'bigint',
    wsBillAddrSk: 'bigint',
    wsShipCustomerSk: 'bigint',
    wsShipCdemoSk: 'bigint',
    wsShipHdemoSk: 'bigint',
    wsShipAddrSk: 'bigint',
    wsWebPageSk: 'bigint',
    wsWebSiteSk: 'bigint',
    wsShipModeSk: 'bigint',
    wsWarehouseSk: 'bigint',
    wsPromoSk: 'bigint',
    wsOrderNumber: 'bigint',
    wsQuantity: 'bigint',
    wsWholesaleCost: 'double',
    wsListPrice: 'double',
    wsSalesPrice: 'double',
    wsExtDiscountAmt: 'double',
    wsExtSalesPrice: 'double',
    wsExtWholesaleCost: 'double',
    wsExtListPrice: 'double',
    wsExtTax: 'double',
    wsCouponAmt: 'double',
    wsExtShipCost: 'double',
    wsNetPaid: 'double',
    wsNetPaidIncTax: 'double',
    wsNetPaidIncShip: 'double',
    wsNetPaidIncShipTax: 'double',
    wsNetProfit: 'double',
  },
  webReturns: {
    wrReturnedDateSk: 'bigint',
    wrReturnedTimeSk: 'bigint',
    wrItemSk: 'bigint',
    wrRefundedCustomerSk: 'bigint',
    wrRefundedCdemoSk: 'bigint',
    wrRefundedHdemoSk: 'bigint',
    wrRefundedAddrSk: 'bigint',
    wrReturningCustomerSk: 'bigint',
    wrReturningCdemoSk: 'bigint',
    wrReturningHdemoSk: 'bigint',
    wrReturningAddrSk: 'bigint',
    wrWebPageSk: 'bigint',
    wrReasonSk: 'bigint',
    wrOrderNumber: 'bigint',
    wrReturnQuantity: 'bigint',
    wrReturnAmt: 'double',
    wrReturnTax: 'double',
    wrReturnAmtIncTax: 'double',
    wrFee: 'double',
    wrReturnShipCost: 'double',
    wrRefundedCash: 'double',
    wrReversedCharge: 'double',
    wrAccountCredit: 'double',
    wrNetLoss: 'double',
  },
  callCenter: {
    ccCallCenterSk: 'bigint',
    ccCallCenterId: 'string',
    ccRecStartDate: 'string',
    ccRecEndDate: 'string',
    ccClosedDateSk: 'bigint',
    ccOpenDateSk: 'bigint',
    ccName: 'string',
    ccClass: 'string',
    ccEmployees: 'bigint',
    ccSqFt: 'bigint',
    ccHours: 'string',
    ccManager: 'string',
    ccMktId: 'bigint',
    ccMktClass: 'string',
    ccMktDesc: 'string',
    ccMarketManager: 'string',
    ccDivision: 'bigint',
    ccDivisionName: 'string',
    ccCompany: 'bigint',
    ccCompanyName: 'string',
    ccStreetNumber: 'string',
    ccStreetName: 'string',
    ccStreetType: 'string',
    ccSuiteNumber: 'string',
    ccCity: 'string',
    ccCounty: 'string',
    ccState: 'string',
    ccZip: 'string',
    ccCountry: 'string',
    ccGmtOffset: 'double',
    ccTaxPercentage: 'double',
  },
  catalogPage: {
    cpCatalogPageSk: 'bigint',
    cpCatalogPageId: 'string',
    cpStartDateSk: 'bigint',
    cpEndDateSk: 'bigint',
    cpDepartment: 'string',
    cpCatalogNumber: 'bigint',
    cpCatalogPageNumber: 'bigint',
    cpDescription: 'string',
    cpType: 'string',
  },
  customer: {
    cCustomerSk: 'bigint',
    cCustomerId: 'string',
    cCurrentCdemoSk: 'bigint',
    cCurrentHdemoSk: 'bigint',
    cCurrentAddrSk: 'bigint',
    cFirstShiptoDateSk: 'bigint',
    cFirstSalesDateSk: 'bigint',
    cSalutation: 'string',
    cFirstName: 'string',
    cLastName: 'string',
    cPreferredCustFlag: 'string',
    cBirthDay: 'bigint',
    cBirthMonth: 'bigint',
    cBirthYear: 'bigint',
    cBirthCountry: 'string',
    cLogin: 'string',
    cEmailAddress: 'string',
    cLastReviewDate: 'string',
  },
  customerAddress: {
    caAddressSk: 'bigint',
    caAddressId: 'string',
    caStreetNumber: 'string',
    caStreetName: 'string',
    caStreetType: 'string',
    caSuiteNumber: 'string',
    caCity: 'string',
    caCounty: 'string',
    caState: 'string',
    caZip: 'string',
    caCountry: 'string',
    caGmtOffset: 'double',
    caLocationType: 'string',
  },
  customerDemographics: {
    cdDemoSk: 'bigint',
    cdGender: 'string',
    cdMaritalStatus: 'string',
    cdEducationStatus: 'string',
    cdPurchaseEstimate: 'bigint',
    cdCreditRating: 'string',
    cdDepCount: 'bigint',
    cdDepEmployedCount: 'bigint',
    cdDepCollegeCount: 'bigint',
  },
  dateDim: {
    dDateSk: 'bigint',
    dDateId: 'string',
    dDate: 'string',
    dMonthSeq: 'bigint',
    dWeekSeq: 'bigint',
    dQuarterSeq: 'bigint',
    dYear: 'bigint',
    dDow: 'bigint',
    dMoy: 'bigint',
    dDom: 'bigint',
    dQoy: 'bigint',
    dFyYear: 'bigint',
    dFyQuarterSeq: 'bigint',
    dFyWeekSeq: 'bigint',
    dDayName: 'string',
    dQuarterName: 'string',
    dHoliday: 'string',
    dWeekend: 'string',
    dFollowingHoliday: 'string',
    dFirstDom: 'bigint',
    dLastDom: 'bigint',
    dSameDayLy: 'bigint',
    dSameDayLq: 'bigint',
    dCurrentDay: 'string',
    dCurrentWeek: 'string',
    dCurrentMonth: 'string',
    dCurrentQuarter: 'string',
    dCurrentYear: 'string',
  },
  householdDemographics: {
    hdDemoSk: 'bigint',
    hdIncomeBandSk: 'bigint',
    hdBuyPotential: 'string',
    hdDepCount: 'bigint',
    hdVehicleCount: 'bigint',
  },
  incomeBand: {
    ibIncomeBandSk: 'bigint',
    ibLowerBound: 'bigint',
    ibUpperBound: 'bigint',
  },
  item: {
    iItemSk: 'bigint',
    iItemId: 'string',
    iRecStartDate: 'string',
    iRecEndDate: 'string',
    iItemDesc: 'string',
    iCurrentPrice: 'double',
    iWholesaleCost: 'double',
    iBrandId: 'bigint',
    iBrand: 'string',
    iClassId: 'bigint',
    iClass: 'string',
    iCategoryId: 'bigint',
    iCategory: 'string',
    iManufactId: 'bigint',
    iManufact: 'string',
    iSize: 'string',
    iFormulation: 'string',
    iColor: 'string',
    iUnits: 'string',
    iContainer: 'string',
    iManagerId: 'bigint',
    iProductName: 'string',
  },
  promotion: {
    pPromoSk: 'bigint',
    pPromoId: 'string',
    pStartDateSk: 'bigint',
    pEndDateSk: 'bigint',
    pItemSk: 'bigint',
    pCost: 'double',
    pResponseTarget: 'bigint',
    pPromoName: 'string',
    pChannelDmail: 'string',
    pChannelEmail: 'string',
    pChannelCatalog: 'string',
    pChannelTv: 'string',
    pChannelRadio: 'string',
    pChannelPress: 'string',
    pChannelEvent: 'string',
    pChannelDemo: 'string',
    pChannelDetails: 'string',
    pPurpose: 'string',
    pDiscountActive: 'string',
  },
  reason: {
    rReasonSk: 'bigint',
    rReasonId: 'string',
    rReasonDesc: 'string',
  },
  shipMode: {
    smShipModeSk: 'bigint',
    smShipModeId: 'string',
    smType: 'string',
    smCode: 'string',
    smCarrier: 'string',
    smContract: 'string',
  },
  store: {
    sStoreSk: 'bigint',
    sStoreId: 'string',
    sRecStartDate: 'string',
    sRecEndDate: 'string',
    sClosedDateSk: 'bigint',
    sStoreName: 'string',
    sNumberEmployees: 'bigint',
    sFloorSpace: 'bigint',
    sHours: 'string',
    sManager: 'string',
    sMarketId: 'bigint',
    sGeographyClass: 'string',
    sMarketDesc: 'string',
    sMarketManager: 'string',
    sDivisionId: 'bigint',
    sDivisionName: 'string',
    sCompanyId: 'bigint',
    sCompanyName: 'string',
    sStreetNumber: 'string',
    sStreetName: 'string',
    sStreetType: 'string',
    sSuiteNumber: 'string',
    sCity: 'string',
    sCounty: 'string',
    sState: 'string',
    sZip: 'string',
    sCountry: 'string',
    sGmtOffset: 'double',
    sTaxPercentage: 'double',
  },
  timeDim: {
    tTimeSk: 'bigint',
    tTimeId: 'string',
    tTime: 'bigint',
    tHour: 'bigint',
    tMinute: 'bigint',
    tSecond: 'bigint',
    tAmPm: 'string',
    tShift: 'string',
    tSubShift: 'string',
    tMealTime: 'string',
  },
  warehouse: {
    wWarehouseSk: 'bigint',
    wWarehouseId: 'string',
    wWarehouseName: 'string',
    wWarehouseSqFt: 'bigint',
    wStreetNumber: 'string',
    wStreetName: 'string',
    wStreetType: 'string',
    wSuiteNumber: 'string',
    wCity: 'string',
    wCounty: 'string',
    wState: 'string',
    wZip: 'string',
    wCountry: 'string',
    wGmtOffset: 'double',
  },
  webPage: {
    wpWebPageSk: 'bigint',
    wpWebPageId: 'string',
    wpRecStartDate: 'string',
    wpRecEndDate: 'string',
    wpCreationDateSk: 'bigint',
    wpAccessDateSk: 'bigint',
    wpAutogenFlag: 'string',
    wpCustomerSk: 'bigint',
    wpUrl: 'string',
    wpType: 'string',
    wpCharCount: 'bigint',
    wpLinkCount: 'bigint',
    wpImageCount: 'bigint',
    wpMaxAdCount: 'bigint',
  },
  webSite: {
    webSiteSk: 'bigint',
    webSiteId: 'string',
    webRecStartDate: 'string',
    webRecEndDate: 'string',
    webName: 'string',
    webOpenDateSk: 'bigint',
    webCloseDateSk: 'bigint',
    webClass: 'string',
    webManager: 'string',
    webMktId: 'bigint',
    webMktClass: 'string',
    webMktDesc: 'string',
    webMarketManager: 'string',
    webCompanyId: 'bigint',
    webCompanyName: 'string',
    webStreetNumber: 'string',
    webStreetName: 'string',
    webStreetType: 'string',
    webSuiteNumber: 'string',
    webCity: 'string',
    webCounty: 'string',
    webState: 'string',
    webZip: 'string',
    webCountry: 'string',
    webGmtOffset: 'string',
    webTaxPercentage: 'double',
  },
};
