import {
  DataTypeExprKind,
  Expression,
} from './expressions';
import * as exp from './expressions';
import {
  enumFromString, isInstanceOf,
} from './port_internals';

// Short keys for serialized payload
const INDEX = 'i';
const ARG_KEY = 'k';
const IS_ARRAY = 'a';
const CLASS = 'c';
const TYPE = 't';
const COMMENTS = 'o';
const META = 'm';
const VALUE = 'v';
const DATA_TYPE = 'DataType.Type';

/**
 * Dump an Expression into a JSON serializable List.
 * Uses an iterative BFS/DFS stack-based approach.
 */
export function dump (expression: Expression): Array<Record<string, unknown>> {
  let i = 0;
  const payloads: Array<Record<string, unknown>> = [];
  const stack: Array<[unknown, number | undefined, string | undefined, boolean]> = [
    [
      expression,
      undefined,
      undefined,
      false,
    ],
  ];

  while (0 < stack.length) {
    const [
      node,
      index,
      argKey,
      isArray,
    ] = stack.pop()!;
    const payload: Record<string, unknown> = {};

    if (index !== undefined) payload[INDEX] = index;
    if (argKey !== undefined) payload[ARG_KEY] = argKey;
    if (isArray) payload[IS_ARRAY] = isArray;

    payloads.push(payload);

    if (node instanceof Expression) {
      // Logic for class naming.
      // In TS, constructors usually match the prefix-free name + Expr suffix
      payload[CLASS] = node.constructor.name;

      if (node.type) {
        if (typeof node === 'string') {
          payload[TYPE] = [node];
        } else if (typeof node.type === 'string') {
          payload[TYPE] = [node.type];
        } else {
          payload[TYPE] = dump(node.type);
        }
      }
      if (node.comments && 0 < node.comments.length) {
        payload[COMMENTS] = node.comments;
      }
      if (node.meta) {
        payload[META] = node.meta;
      }

      if (node.args) {
        const entries = Object.entries(node.args).reverse();
        for (const [k, vs] of entries) {
          if (Array.isArray(vs)) {
            for (let j = vs.length - 1; 0 <= j; j--) {
              stack.push([
                vs[j],
                i,
                k,
                true,
              ]);
            }
          } else if (vs !== undefined && vs !== undefined) {
            stack.push([
              vs,
              i,
              k,
              false,
            ]);
          }
        }
      }
    } else if (node && typeof node === 'object' && 'value' in node) {
      // Handling for DataType enum types
      payload[CLASS] = DATA_TYPE;
      payload[VALUE] = node.value;
    } else {
      // Primitive values (strings, numbers, etc.)
      payload[VALUE] = node;
    }

    i++;
  }

  return payloads;
}

/**
 * Load a list of dicts generated by dump into an Expression.
 */
export function load (payloads?: Record<string, unknown>[]): Expression | undefined {
  if (!payloads || payloads.length === 0) {
    return undefined;
  }

  const [rootPayload, ...tail] = payloads;
  const root = _load(rootPayload);

  if (!(root instanceof Expression)) return undefined;

  const nodes: Expression[] = [root];

  for (const payload of tail) {
    const node = _load(payload);
    if (isInstanceOf(node, Expression)) {
      nodes.push(node);
    }

    const parent = nodes[payload[INDEX] as number];
    const argKey = payload[ARG_KEY] as string;

    if (payload[IS_ARRAY]) {
      parent.append(argKey, node);
    } else {
      parent.setArgKey(argKey, node);
    }
  }

  return root;
}

/**
 * Internal helper to instantiate the correct class from a payload.
 */
function _load (payload: Record<string, unknown>): Expression | DataTypeExprKind {
  const className = payload[CLASS];

  if (!className) {
    return payload[VALUE] as Expression | DataTypeExprKind;
  }

  if (className === DATA_TYPE) {
    return enumFromString(DataTypeExprKind, payload[VALUE] as string)!;
  }

  // Registry-based lookup is safer than eval() or dynamic imports in TS
  // Assuming you have a registry of all Expression classes
  const ExprClass = exp[className as keyof typeof exp];
  if (typeof ExprClass !== 'function' || !(ExprClass.prototype instanceof Expression)) {
    throw new Error(`Unknown expression class: ${className}`);
  }

  const expression = new (ExprClass as typeof Expression)({});

  if (payload[TYPE]) {
    expression.type = load(payload[TYPE] as Record<string, unknown>[]);
  }
  if (payload[COMMENTS]) {
    expression.comments = payload[COMMENTS] as string[];
  }
  if (payload[META]) {
    expression.meta = payload[META] as Record<string, unknown>;
  }

  return expression;
}
