// https://github.com/tobymao/sqlglot/blob/264e95f04d95f2cd7bcf255ee7ae160db36882a7/sqlglot/time.py

import { DateTime } from 'luxon';
import {
  TrieResult, inTrie, newTrie, type TrieNode,
} from './trie';

/**
 * Formats a time string by replacing tokens with mapped values.
 *
 * Uses a trie-based algorithm to efficiently match and replace format tokens.
 * The generic time format is based on Python's time.strftime.
 *
 * @param string - The format string to process
 * @param mapping - Record mapping format tokens to their replacements
 * @param trie - Optional pre-built trie for the mapping keys (built automatically if not provided)
 * @returns The formatted string, or undefined if input is empty
 *
 * @example
 * ```ts
 * formatTime("%Y-%m-%d", { "%Y": "2024", "%m": "01", "%d": "15" });
 * // "2024-01-15"
 * ```
 *
 */
export function formatTime (
  string: string,
  mapping: Record<string, string>,
  trie?: TrieNode,
): string | undefined {
  if (!string) {
    return undefined;
  }

  let start = 0;
  let end = 1;
  const size = string.length;
  const trieToUse = trie ?? newTrie(Object.keys(mapping).map((k) => Array.from(k)));
  let current = trieToUse;
  const chunks: string[] = [];
  let sym: string | undefined;

  while (end <= size) {
    let chars = string.substring(start, end);
    const [result, newCurrent] = inTrie(current, [chars[chars.length - 1]]);
    current = newCurrent;

    if (result === TrieResult.FAILED) {
      if (sym) {
        end -= 1;
        chars = sym;
        sym = undefined;
      } else {
        chars = chars[0];
        end = start + 1;
      }

      start += chars.length;
      chunks.push(chars);
      current = trieToUse;
    } else if (result === TrieResult.EXISTS) {
      sym = chars;
    }

    end += 1;

    if (result !== TrieResult.FAILED && size < end) {
      chunks.push(chars);
    }
  }

  return chunks.map((chunk) => mapping[chunk] ?? chunk).join('');
}

// https://github.com/tobymao/sqlglot/blob/264e95f04d95f2cd7bcf255ee7ae160db36882a7/sqlglot/time.py#L64
export const TIMEZONES = new Set([
  'africa/abidjan',
  'africa/accra',
  'africa/addis_ababa',
  'africa/algiers',
  'africa/asmara',
  'africa/asmera',
  'africa/bamako',
  'africa/bangui',
  'africa/banjul',
  'africa/bissau',
  'africa/blantyre',
  'africa/brazzaville',
  'africa/bujumbura',
  'africa/cairo',
  'africa/casablanca',
  'africa/ceuta',
  'africa/conakry',
  'africa/dakar',
  'africa/dar_es_salaam',
  'africa/djibouti',
  'africa/douala',
  'africa/el_aaiun',
  'africa/freetown',
  'africa/gaborone',
  'africa/harare',
  'africa/johannesburg',
  'africa/juba',
  'africa/kampala',
  'africa/khartoum',
  'africa/kigali',
  'africa/kinshasa',
  'africa/lagos',
  'africa/libreville',
  'africa/lome',
  'africa/luanda',
  'africa/lubumbashi',
  'africa/lusaka',
  'africa/malabo',
  'africa/maputo',
  'africa/maseru',
  'africa/mbabane',
  'africa/mogadishu',
  'africa/monrovia',
  'africa/nairobi',
  'africa/ndjamena',
  'africa/niamey',
  'africa/nouakchott',
  'africa/ouagadougou',
  'africa/porto-novo',
  'africa/sao_tome',
  'africa/timbuktu',
  'africa/tripoli',
  'africa/tunis',
  'africa/windhoek',
  'america/adak',
  'america/anchorage',
  'america/anguilla',
  'america/antigua',
  'america/araguaina',
  'america/argentina/buenos_aires',
  'america/argentina/catamarca',
  'america/argentina/comodrivadavia',
  'america/argentina/cordoba',
  'america/argentina/jujuy',
  'america/argentina/la_rioja',
  'america/argentina/mendoza',
  'america/argentina/rio_gallegos',
  'america/argentina/salta',
  'america/argentina/san_juan',
  'america/argentina/san_luis',
  'america/argentina/tucuman',
  'america/argentina/ushuaia',
  'america/aruba',
  'america/asuncion',
  'america/atikokan',
  'america/atka',
  'america/bahia',
  'america/bahia_banderas',
  'america/barbados',
  'america/belem',
  'america/belize',
  'america/blanc-sablon',
  'america/boa_vista',
  'america/bogota',
  'america/boise',
  'america/buenos_aires',
  'america/cambridge_bay',
  'america/campo_grande',
  'america/cancun',
  'america/caracas',
  'america/catamarca',
  'america/cayenne',
  'america/cayman',
  'america/chicago',
  'america/chihuahua',
  'america/ciudad_juarez',
  'america/coral_harbour',
  'america/cordoba',
  'america/costa_rica',
  'america/creston',
  'america/cuiaba',
  'america/curacao',
  'america/danmarkshavn',
  'america/dawson',
  'america/dawson_creek',
  'america/denver',
  'america/detroit',
  'america/dominica',
  'america/edmonton',
  'america/eirunepe',
  'america/el_salvador',
  'america/ensenada',
  'america/fort_nelson',
  'america/fort_wayne',
  'america/fortaleza',
  'america/glace_bay',
  'america/godthab',
  'america/goose_bay',
  'america/grand_turk',
  'america/grenada',
  'america/guadeloupe',
  'america/guatemala',
  'america/guayaquil',
  'america/guyana',
  'america/halifax',
  'america/havana',
  'america/hermosillo',
  'america/indiana/indianapolis',
  'america/indiana/knox',
  'america/indiana/marengo',
  'america/indiana/petersburg',
  'america/indiana/tell_city',
  'america/indiana/vevay',
  'america/indiana/vincennes',
  'america/indiana/winamac',
  'america/indianapolis',
  'america/inuvik',
  'america/iqaluit',
  'america/jamaica',
  'america/jujuy',
  'america/juneau',
  'america/kentucky/louisville',
  'america/kentucky/monticello',
  'america/knox_in',
  'america/kralendijk',
  'america/la_paz',
  'america/lima',
  'america/los_angeles',
  'america/louisville',
  'america/lower_princes',
  'america/maceio',
  'america/managua',
  'america/manaus',
  'america/marigot',
  'america/martinique',
  'america/matamoros',
  'america/mazatlan',
  'america/mendoza',
  'america/menominee',
  'america/merida',
  'america/metlakatla',
  'america/mexico_city',
  'america/miquelon',
  'america/moncton',
  'america/monterrey',
  'america/montevideo',
  'america/montreal',
  'america/montserrat',
  'america/nassau',
  'america/new_york',
  'america/nipigon',
  'america/nome',
  'america/noronha',
  'america/north_dakota/beulah',
  'america/north_dakota/center',
  'america/north_dakota/new_salem',
  'america/nuuk',
  'america/ojinaga',
  'america/panama',
  'america/pangnirtung',
  'america/paramaribo',
  'america/phoenix',
  'america/port-au-prince',
  'america/port_of_spain',
  'america/porto_acre',
  'america/porto_velho',
  'america/puerto_rico',
  'america/punta_arenas',
  'america/rainy_river',
  'america/rankin_inlet',
  'america/recife',
  'america/regina',
  'america/resolute',
  'america/rio_branco',
  'america/rosario',
  'america/santa_isabel',
  'america/santarem',
  'america/santiago',
  'america/santo_domingo',
  'america/sao_paulo',
  'america/scoresbysund',
  'america/shiprock',
  'america/sitka',
  'america/st_barthelemy',
  'america/st_johns',
  'america/st_kitts',
  'america/st_lucia',
  'america/st_thomas',
  'america/st_vincent',
  'america/swift_current',
  'america/tegucigalpa',
  'america/thule',
  'america/thunder_bay',
  'america/tijuana',
  'america/toronto',
  'america/tortola',
  'america/vancouver',
  'america/virgin',
  'america/whitehorse',
  'america/winnipeg',
  'america/yakutat',
  'america/yellowknife',
  'antarctica/casey',
  'antarctica/davis',
  'antarctica/dumontdurville',
  'antarctica/macquarie',
  'antarctica/mawson',
  'antarctica/mcmurdo',
  'antarctica/palmer',
  'antarctica/rothera',
  'antarctica/south_pole',
  'antarctica/syowa',
  'antarctica/troll',
  'antarctica/vostok',
  'arctic/longyearbyen',
  'asia/aden',
  'asia/almaty',
  'asia/amman',
  'asia/anadyr',
  'asia/aqtau',
  'asia/aqtobe',
  'asia/ashgabat',
  'asia/ashkhabad',
  'asia/atyrau',
  'asia/baghdad',
  'asia/bahrain',
  'asia/baku',
  'asia/bangkok',
  'asia/barnaul',
  'asia/beirut',
  'asia/bishkek',
  'asia/brunei',
  'asia/calcutta',
  'asia/chita',
  'asia/choibalsan',
  'asia/chongqing',
  'asia/chungking',
  'asia/colombo',
  'asia/dacca',
  'asia/damascus',
  'asia/dhaka',
  'asia/dili',
  'asia/dubai',
  'asia/dushanbe',
  'asia/famagusta',
  'asia/gaza',
  'asia/harbin',
  'asia/hebron',
  'asia/ho_chi_minh',
  'asia/hong_kong',
  'asia/hovd',
  'asia/irkutsk',
  'asia/istanbul',
  'asia/jakarta',
  'asia/jayapura',
  'asia/jerusalem',
  'asia/kabul',
  'asia/kamchatka',
  'asia/karachi',
  'asia/kashgar',
  'asia/kathmandu',
  'asia/katmandu',
  'asia/khandyga',
  'asia/kolkata',
  'asia/krasnoyarsk',
  'asia/kuala_lumpur',
  'asia/kuching',
  'asia/kuwait',
  'asia/macao',
  'asia/macau',
  'asia/magadan',
  'asia/makassar',
  'asia/manila',
  'asia/muscat',
  'asia/nicosia',
  'asia/novokuznetsk',
  'asia/novosibirsk',
  'asia/omsk',
  'asia/oral',
  'asia/phnom_penh',
  'asia/pontianak',
  'asia/pyongyang',
  'asia/qatar',
  'asia/qostanay',
  'asia/qyzylorda',
  'asia/rangoon',
  'asia/riyadh',
  'asia/saigon',
  'asia/sakhalin',
  'asia/samarkand',
  'asia/seoul',
  'asia/shanghai',
  'asia/singapore',
  'asia/srednekolymsk',
  'asia/taipei',
  'asia/tashkent',
  'asia/tbilisi',
  'asia/tehran',
  'asia/tel_aviv',
  'asia/thimbu',
  'asia/thimphu',
  'asia/tokyo',
  'asia/tomsk',
  'asia/ujung_pandang',
  'asia/ulaanbaatar',
  'asia/ulan_bator',
  'asia/urumqi',
  'asia/ust-nera',
  'asia/vientiane',
  'asia/vladivostok',
  'asia/yakutsk',
  'asia/yangon',
  'asia/yekaterinburg',
  'asia/yerevan',
  'atlantic/azores',
  'atlantic/bermuda',
  'atlantic/canary',
  'atlantic/cape_verde',
  'atlantic/faeroe',
  'atlantic/faroe',
  'atlantic/jan_mayen',
  'atlantic/madeira',
  'atlantic/reykjavik',
  'atlantic/south_georgia',
  'atlantic/st_helena',
  'atlantic/stanley',
  'australia/act',
  'australia/adelaide',
  'australia/brisbane',
  'australia/broken_hill',
  'australia/canberra',
  'australia/currie',
  'australia/darwin',
  'australia/eucla',
  'australia/hobart',
  'australia/lhi',
  'australia/lindeman',
  'australia/lord_howe',
  'australia/melbourne',
  'australia/nsw',
  'australia/north',
  'australia/perth',
  'australia/queensland',
  'australia/south',
  'australia/sydney',
  'australia/tasmania',
  'australia/victoria',
  'australia/west',
  'australia/yancowinna',
  'brazil/acre',
  'brazil/denoronha',
  'brazil/east',
  'brazil/west',
  'cet',
  'cst6cdt',
  'canada/atlantic',
  'canada/central',
  'canada/eastern',
  'canada/mountain',
  'canada/newfoundland',
  'canada/pacific',
  'canada/saskatchewan',
  'canada/yukon',
  'chile/continental',
  'chile/easterisland',
  'cuba',
  'eet',
  'est',
  'est5edt',
  'egypt',
  'eire',
  'etc/gmt',
  'etc/gmt+0',
  'etc/gmt+1',
  'etc/gmt+10',
  'etc/gmt+11',
  'etc/gmt+12',
  'etc/gmt+2',
  'etc/gmt+3',
  'etc/gmt+4',
  'etc/gmt+5',
  'etc/gmt+6',
  'etc/gmt+7',
  'etc/gmt+8',
  'etc/gmt+9',
  'etc/gmt-0',
  'etc/gmt-1',
  'etc/gmt-10',
  'etc/gmt-11',
  'etc/gmt-12',
  'etc/gmt-13',
  'etc/gmt-14',
  'etc/gmt-2',
  'etc/gmt-3',
  'etc/gmt-4',
  'etc/gmt-5',
  'etc/gmt-6',
  'etc/gmt-7',
  'etc/gmt-8',
  'etc/gmt-9',
  'etc/gmt0',
  'etc/greenwich',
  'etc/uct',
  'etc/utc',
  'etc/universal',
  'etc/zulu',
  'europe/amsterdam',
  'europe/andorra',
  'europe/astrakhan',
  'europe/athens',
  'europe/belfast',
  'europe/belgrade',
  'europe/berlin',
  'europe/bratislava',
  'europe/brussels',
  'europe/bucharest',
  'europe/budapest',
  'europe/busingen',
  'europe/chisinau',
  'europe/copenhagen',
  'europe/dublin',
  'europe/gibraltar',
  'europe/guernsey',
  'europe/helsinki',
  'europe/isle_of_man',
  'europe/istanbul',
  'europe/jersey',
  'europe/kaliningrad',
  'europe/kiev',
  'europe/kirov',
  'europe/kyiv',
  'europe/lisbon',
  'europe/ljubljana',
  'europe/london',
  'europe/luxembourg',
  'europe/madrid',
  'europe/malta',
  'europe/mariehamn',
  'europe/minsk',
  'europe/monaco',
  'europe/moscow',
  'europe/nicosia',
  'europe/oslo',
  'europe/paris',
  'europe/podgorica',
  'europe/prague',
  'europe/riga',
  'europe/rome',
  'europe/samara',
  'europe/san_marino',
  'europe/sarajevo',
  'europe/saratov',
  'europe/simferopol',
  'europe/skopje',
  'europe/sofia',
  'europe/stockholm',
  'europe/tallinn',
  'europe/tirane',
  'europe/tiraspol',
  'europe/ulyanovsk',
  'europe/uzhgorod',
  'europe/vaduz',
  'europe/vatican',
  'europe/vienna',
  'europe/vilnius',
  'europe/volgograd',
  'europe/warsaw',
  'europe/zagreb',
  'europe/zaporozhye',
  'europe/zurich',
  'gb',
  'gb-eire',
  'gmt',
  'gmt+0',
  'gmt-0',
  'gmt0',
  'greenwich',
  'hst',
  'hongkong',
  'iceland',
  'indian/antananarivo',
  'indian/chagos',
  'indian/christmas',
  'indian/cocos',
  'indian/comoro',
  'indian/kerguelen',
  'indian/mahe',
  'indian/maldives',
  'indian/mauritius',
  'indian/mayotte',
  'indian/reunion',
  'iran',
  'israel',
  'jamaica',
  'japan',
  'kwajalein',
  'libya',
  'met',
  'mst',
  'mst7mdt',
  'mexico/bajanorte',
  'mexico/bajasur',
  'mexico/general',
  'nz',
  'nz-chat',
  'navajo',
  'prc',
  'pst8pdt',
  'pacific/apia',
  'pacific/auckland',
  'pacific/bougainville',
  'pacific/chatham',
  'pacific/chuuk',
  'pacific/easter',
  'pacific/efate',
  'pacific/enderbury',
  'pacific/fakaofo',
  'pacific/fiji',
  'pacific/funafuti',
  'pacific/galapagos',
  'pacific/gambier',
  'pacific/guadalcanal',
  'pacific/guam',
  'pacific/honolulu',
  'pacific/johnston',
  'pacific/kanton',
  'pacific/kiritimati',
  'pacific/kosrae',
  'pacific/kwajalein',
  'pacific/majuro',
  'pacific/marquesas',
  'pacific/midway',
  'pacific/nauru',
  'pacific/niue',
  'pacific/norfolk',
  'pacific/noumea',
  'pacific/pago_pago',
  'pacific/palau',
  'pacific/pitcairn',
  'pacific/pohnpei',
  'pacific/ponape',
  'pacific/port_moresby',
  'pacific/rarotonga',
  'pacific/saipan',
  'pacific/samoa',
  'pacific/tahiti',
  'pacific/tarawa',
  'pacific/tongatapu',
  'pacific/truk',
  'pacific/wake',
  'pacific/wallis',
  'pacific/yap',
  'poland',
  'portugal',
  'roc',
  'rok',
  'singapore',
  'turkey',
  'uct',
  'us/alaska',
  'us/aleutian',
  'us/arizona',
  'us/central',
  'us/east-indiana',
  'us/eastern',
  'us/hawaii',
  'us/indiana-starke',
  'us/michigan',
  'us/mountain',
  'us/pacific',
  'us/samoa',
  'utc',
  'universal',
  'w-su',
  'wet',
  'zulu',
]);

/**
 * Determines the subsecond precision of an ISO-8601 timestamp literal.
 *
 * Parses a timestamp string like '2023-01-01 12:13:14.123456+00:00' and returns
 * the precision level for constructing types like DATETIME(6).
 *
 * @param timestampLiteral - An ISO-8601 timestamp string
 * @returns 0 (no subseconds), 3 (milliseconds), or 6 (microseconds)
 *
 * @example
 * ```ts
 * subsecondPrecision("2023-01-01 12:13:14"); // 0
 * subsecondPrecision("2023-01-01 12:13:14.123"); // 3
 * subsecondPrecision("2023-01-01 12:13:14.123456"); // 6
 * subsecondPrecision("2023-01-01 12:13:14.1234"); // 6
 * ```
 *
 */
export function subsecondPrecision (timestampLiteral: string): number {
  try {
    const parsed = DateTime.fromISO(timestampLiteral);
    if (!parsed.isValid) {
      return 0;
    }

    // Extract fractional seconds from the timestamp string
    const match = timestampLiteral.match(/\.(\d+)/);
    if (!match) {
      return 0;
    }

    const fractionalPart = match[1].replace(/0+$/, '');
    const subsecondDigitCount = fractionalPart.length;

    if (3 < subsecondDigitCount) {
      return 6;
    } else if (0 < subsecondDigitCount) {
      return 3;
    }
    return 0;
  } catch {
    return 0;
  }
}
