export enum DbmlKind {
  SCHEMA = 'schema',
  PROJECT = 'project',
  TABLE = 'table',
  COLUMN = 'column',
  COLUMN_TYPE = 'columnType',
  INDEX = 'index',
  INDEX_COLUMN = 'indexColumn',
  CHECK = 'check',
  ENUM = 'enum',
  ENUM_VALUE = 'enumValue',
  REF = 'ref',
  INLINE_REF = 'inlineRef',
  ENDPOINT = 'endpoint',
  TABLE_GROUP = 'tableGroup',
  TABLE_GROUP_FIELD = 'tableGroupField',
  STICKY_NOTE = 'stickyNote',
  RECORD = 'record',
}
